repositories {
	maven {
		name = "SquidDev"
		url = "https://squiddev.cc/maven/"
	}
    maven {	url = "https://maven.blamejared.com/" }
    maven { url = "https://teamopenindustry.cc/maven" }
}

sourceSets {
	main {
		java {
			srcDir "ImmersiveRailroadingIntegration/src/main/java"
		}
	}
}

dependencies {
	compileOnly "cc.tweaked:cc-tweaked-1.20.4-forge:1.110.2"
	compileOnly "blusunrize.immersiveengineering:ImmersiveEngineering:1.20.4-11.7.0-184"
	implementation "blusunrize.immersiveengineering:ImmersiveEngineering:1.20.4-11.7.0-184:datagen"
	implementation "trackapi:TrackAPI:1.20.4-neoforge-1.2-c5a4c3"
}
