repositories {
	maven {
		url "https://maven.squiddev.cc"
		content {
			includeGroup("cc.tweaked")
		}
	}
	maven {
		url = "https://maven.blamejared.com/"
	}
	maven {
		url = "https://cursemaven.com"
	}
	maven { url = "https://teamopenindustry.cc/maven" }
}

sourceSets {
	main {
		java {
			srcDir "ImmersiveRailroadingIntegration/src/main/java"
		}
	}
}

dependencies {
	modImplementation "cc.tweaked:cc-tweaked-1.21.1-forge:1.116.2"
	modImplementation "curse.maven:immersive-engineering-231951:6733669"
	modImplementation "trackapi:TrackAPI:1.21.1-neoforge-1.3"
}
