repositories {
	maven {
		name = "SquidDev"
		url = "https://squiddev.cc/maven/"
	}
	maven {	
		url = "https://maven.blamejared.com/" 
	}
	maven {
		url = "https://cursemaven.com"
	}
	maven { url = "https://teamopenindustry.cc/maven" }
}

sourceSets {
	main {
		java {
			srcDir "ImmersiveRailroadingIntegration/src/main/java"
		}
	}
}

dependencies {
	modImplementation "org.squiddev:cc-tweaked-1.17.1:1.100.4"
	modImplementation "blusunrize.immersiveengineering:ImmersiveEngineering:1.17.1-5.0.2-pre.306"
	modImplementation "trackapi:TrackAPI:1.17.1-forge-1.3"
}
